# Generated by Django 6.0.6 on 2026-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What she did there')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current job', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='e.g. Certified Accountant | Financial Analyst', max_length=300)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='profile/')),
                ('cv', models.FileField(blank=True, help_text='Optional downloadable CV', null=True, upload_to='cv/')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('accounting', 'Accounting'), ('software', 'Software & Tools'), ('finance', 'Finance'), ('other', 'Other')], default='accounting', max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Percentage 0–100, used to render a progress bar')),
            ],
            options={
                'ordering': ['category', '-proficiency'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated, e.g. QuickBooks, Excel, SAP', max_length=300),
        ),
    ]
